#ifndef PROJECT_CONF_H_
#define PROJECT_CONF_H_

#define PRINT_WITH_FUNC_LINE 0

#define LOG_LEVEL_CONF_HASH_TABLE LOG_LEVEL_INFO
#define LOG_LEVEL_CONF_BITMAP     LOG_LEVEL_INFO
#define LOG_LEVEL_CONF_PERSON     LOG_LEVEL_INFO
#define LOG_LEVEL_CONF_TEST       LOG_LEVEL_INFO

#endif /* PROJECT_CONF_H_ */
