#ifndef PROJECT_CONF_H_
#define PROJECT_CONF_H_

#define PRINT_WITH_FUNC_LINE 0

#define LOG_LEVEL_CONF_LIST LOG_LEVEL_INFO
#define LOG_LEVEL_CONF_NODE LOG_LEVEL_INFO
#define LOG_LEVEL_CONF_TEST LOG_LEVEL_INFO

#endif /* PROJECT_CONF_H_ */
